language: python
python:
    - "2.7.9"
addons:
    apt:
        packages:
            - xsltproc
before_install:
    - export LD_LIBRARY_PATH=$HOME/lirc_install/lib:$HOME/qt_install/lib
    - export LIBRARY_PATH=$HOME/lirc_install/lib:$HOME/qt_install/lib
    - export CPATH=$HOME/lirc_install/include:$HOME/qt_install/include
    - export PYTHONPATH=$PYTHONPATH:$HOME/qt_install/lib/python2.7/site-packages
    - ./travis.sh
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
cache:
    pip: true
    directories:
        - $HOME/lirc_install
        - $HOME/qt_install
script: make test
notifications:
    email: false
