language: python
python:
  - "2.7"
install:
  - pip install "pyserial==2.7"
  - pip install xbee
  - pip install pymavlink
  - pip install mavproxy
  - pip install dronekit
  - pip install PyOpenGL
  - pip install simpleparse
  - pip install PyVRML97
  - pip install PyDispatcher
script: python -m unittest discover -s tests -p "*.py" -t ..
notifications:
  email: false
