language: python
python:
  - "2.7"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install pyserial
  - pip install matplotlib
  - pip install RPi.GPIO
  - pip install xbee
script: python -m unittest discover -s tests -p "*.py" -t ..
notifications:
  email: false
